services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 112233
      POSTGRES_MULTIPLE_DATABASES: sn_user,sn_posts,sn_auth
    ports:
      - "5444:5432"
    volumes:
      - ./migrations/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
      - ./db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.0.3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - 15672:5672

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ports:
      - "6379:6379"

  flyway-user:
    image: flyway/flyway:latest
    depends_on:
      - db
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/sn_user
      - FLYWAY_USER=dev
      - FLYWAY_PASSWORD=112233
    volumes:
      - ./migrations/sn-user:/flyway/sql
    entrypoint: ["flyway", "migrate"]

  flyway-post:
    image: flyway/flyway:latest
    depends_on:
      - db
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/c
      - FLYWAY_USER=dev
      - FLYWAY_PASSWORD=112233
    volumes:
      - ./migrations/sn-posts:/flyway/sql
    entrypoint: [ "flyway", "migrate" ]

  flyway-auth:
    image: flyway/flyway:latest
    depends_on:
      - db
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/sn_auth
      - FLYWAY_USER=dev
      - FLYWAY_PASSWORD=112233
    volumes:
      - ./migrations/sn-auth:/flyway/sql
    entrypoint: [ "flyway", "migrate" ]
